### ISSUE TITLE
Hal39 crashes, Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE

### ISSUE THREAD

**Issue by apfohl** [netz39/hal39#13]
From time to time, hal39 crashes. I've not yet found out what's the problem.

Trace:
2013-10-18T11:36:16.151236+00:00 app[web.1]:   at SecurePair.EventEmitter.emit (events.js:92:17)
2013-10-18T11:36:16.151228+00:00 app[web.1]:   at SecurePair.<anonymous> (tls.js:1356:32)
2013-10-18T11:36:16.151249+00:00 app[web.1]:   at CleartextStream.read [as _read](tls.js:462:15)
2013-10-18T11:36:16.151262+00:00 app[web.1]:   at EncryptedStream.write [as _write](tls.js:366:25)
2013-10-18T11:36:16.150974+00:00 app[web.1]: events.js:72
2013-10-18T11:36:16.151192+00:00 app[web.1]:               ^
2013-10-18T11:36:16.151221+00:00 app[web.1]: Error: UNABLE_TO_VERIFY_LEAF_SIGNATURE
2013-10-18T11:36:16.151178+00:00 app[web.1]:         throw er; // Unhandled 'error' event
2013-10-18T11:36:16.151268+00:00 app[web.1]:   at doWrite (_stream_writable.js:221:10)
2013-10-18T11:36:16.151254+00:00 app[web.1]:   at CleartextStream.Readable.read (_stream_readable.js:320:10)
2013-10-18T11:36:16.151296+00:00 app[web.1]:   at writeOrBuffer (_stream_writable.js:211:5)
2013-10-18T11:36:16.151309+00:00 app[web.1]:   at write (_stream_readable.js:583:24)
2013-10-18T11:36:16.151316+00:00 app[web.1]:   at flow (_stream_readable.js:592:7)
2013-10-18T11:36:16.151327+00:00 app[web.1]:   at Socket.pipeOnReadable (_stream_readable.js:624:5)
2013-10-18T11:36:16.151302+00:00 app[web.1]:   at EncryptedStream.Writable.write (_stream_writable.js:180:11)
2013-10-18T11:36:16.151241+00:00 app[web.1]:   at SecurePair.maybeInitFinished (tls.js:968:10)
2013-10-18T11:36:16.151392+00:00 app[web.1]: 
2013-10-18T11:36:16.151365+00:00 app[web.1]:   at readableAddChunk (_stream_readable.js:165:9)
2013-10-18T11:36:16.151335+00:00 app[web.1]:   at Socket.EventEmitter.emit (events.js:92:17)
2013-10-18T11:36:16.151354+00:00 app[web.1]:   at emitReadable (_stream_readable.js:404:5)
2013-10-18T11:36:16.151386+00:00 app[web.1]:   at TCP.onread (net.js:526:21)
2013-10-18T11:36:16.151346+00:00 app[web.1]:   at emitReadable_ (_stream_readable.js:408:10)
2013-10-18T11:36:16.151373+00:00 app[web.1]:   at Socket.Readable.push (_stream_readable.js:127:10)
2013-10-18T11:36:17.216903+00:00 heroku[web.1]: Process exited with status 8

**Comment by apfohl** [comment]
I just found out. The problem is part of the web.coffee plugin. If HAL39 tries to connect to an https website which provides an invalid certificate, HAL crashes.

**Comment by apfohl** [comment]
Thx to @bastinat0r for the tip with the environment variable.

NODE_TLS_REJECT_UNAUTHORIZED="0"

is now in Heroku config.
