### ISSUE TITLE
Error: getaddrinfo EADDRINFO

### ISSUE THREAD

**Issue by apfohl** [netz39/hal39#14]
2013-10-24T19:41:45.181769+00:00 app[web.1]: From LeSpocky to #netz39: stick together team!
2013-10-24T19:59:21.675532+00:00 app[web.1]: Error: getaddrinfo EADDRINFO
2013-10-24T19:59:21.675221+00:00 app[web.1]: events.js:72
2013-10-24T19:59:21.675472+00:00 app[web.1]:         throw er; // Unhandled 'error' event
2013-10-24T19:59:21.675539+00:00 app[web.1]:   at errnoException (dns.js:37:11)
2013-10-24T19:59:21.675513+00:00 app[web.1]:               ^
2013-10-24T19:59:21.675563+00:00 app[web.1]: 
2013-10-24T19:59:21.675143+00:00 app[web.1]: 
2013-10-24T19:59:21.675556+00:00 app[web.1]:   at Object.onanswer [as oncomplete](dns.js:124:16)
2013-10-24T19:59:22.794985+00:00 heroku[web.1]: Process exited with status 8
2013-10-24T19:59:22.810519+00:00 heroku[web.1]: State changed from up to crashed

**Comment by apfohl** [comment]
This error occurs, if a domain can not be resolved to its IP.
